stages:
  - build
  - publish

.android-sdk:
  image: gitlab.com/evosverse/noctua/dependency_proxy/containers/cimg/android:2024.07.1
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: always
    - changes:
        - gitlab-ci.yml
        - android/sdk/**/*
      when: always
  before_script:
    - chmod +x gradlew

build-android-sdk:
  extends: .android-sdk
  stage: build
  script:
    - cd android
    - gradle :sdk:build
  only:
    - main

publish-android-sdk:
  extends: .android-sdk
  stage: publish
  script:
    - cd android
    - ./gradlew :sdk:publishDebugPublicationToMavenRepository
  dependencies:
    - build
  only:
    - main