platform :ios, "15.0"
workspace "NoctuaSDKExample.xcworkspace"
use_frameworks!

target "NoctuaSDKExample" do
  project "NoctuaSDKExample/NoctuaSDKExample.xcodeproj"
  pod "NoctuaSDK", :path => ".."
  pod "NoctuaSDK/AdjustSDK", :path => ".."
  pod "NoctuaSDK/FirebaseAnalytics", :path => ".."
  pod "NoctuaSDK/FirebaseCrashlytics", :path => ".."
  pod "NoctuaSDK/FirebaseMessaging", :path => ".."
  pod "NoctuaSDK/FirebaseRemoteConfig", :path => ".."
  pod "NoctuaSDK/FacebookSDK", :path => ".."
end
