platform :ios, "14.0"
workspace "NoctuaSDKExample.xcworkspace"
use_frameworks!

target "NoctuaSDKExample" do
  project "NoctuaSDKExample/NoctuaSDKExample.xcodeproj"
  pod "NoctuaSDK", :path => ".."
  pod "NoctuaSDK/Adjust", :path => ".."
  pod "NoctuaSDK/FirebaseAnalytics", :path => ".."
  pod "NoctuaSDK/FirebaseCrashlytics", :path => ".."
  pod "NoctuaSDK/FacebookSDK", :path => ".."
end
